- name: Creating CSV file
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Clients
  set_fact:
    clients:
      - id: 1
        razao_social: "Testador"
        nome_fantasia: "teste"

      - id: 2
        razao_social: "TesteNovoTeste"
        nome_fantasia: "novo"

- name: Creating CSV file
  set_fact:
    csv_content: |
      | id | Razao Social | Nome Fantasia |
      {% for client in clients %}
      {{ client.id }},{{ client.razao_social }},{{ client.nome_fantasia }}
      {% endfor %}

- name: Save CSV file
  copy:
    content: "{{ csv_content }}"
    dest: /etc/ansible/roles/csv_report.csv
    mode: '0644'
