- name: Insert line into files
  hosts: allHosts
  become: true # Run with root privileges

  tasks:
    - name: Insert Hiiiiiii below Hello World
      ansible.builtin.lineinfile:
        path: /var/www/index.html # File to be edited
        insertafter: '<h1>Hello, World!</h1>' # Insert below this line
        line: '    <p>Hiiiiiii</p>' # Word for insertion
