- name: Install speedtest
  hosts: allHosts
  become: true # Run with root privileges

  tasks:
    - name: Installing speedtest on remote server
      ansible.builtin.apt:
        name: speedtest-cli
